sudo: required
language: generic
#branches to build
branches:
  only:
    - main
services:
  - docker
  - xvfb

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Log in to heroku
  - docker login -u "$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com

install:
  - docker build -t sagarbasavaraj/github-repos-web -f Dockerfile.dev .

script:
  # build production image
  - docker run -e CI=true sagarbasavaraj/github-repos-web npm run test

after_success:
  - docker build -t sagarbasavaraj/github-repos-web .
  - docker tag sagarbasavaraj/github-repos-web registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push sagarbasavaraj/github-repos-web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - heroku container:release web --app $HEROKU_APP_NAME
